<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    
    $_helper    = $this->helper('catalog/output');
    //$_category_helper = Mage::helper('catalog/category');
    $_category  = $this->getCurrentCategory();
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtocart', $code);
    $_showcartbutton = Mage::getStoreConfig('porto_settings/category_grid/show_addtolinks', $code);
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $_imgHtml ?>
<!--
<?php $_categories = $_category->getChildrenCategories() ?>
<?php if (count($_categories) > 0): ?>
    <ul>
        <?php foreach($_categories as $category): ?>
            <?php header('Location:'.$_category_helper->getCategoryUrl($category));die(); ?>
            <li>
                <a href="<?php echo $_category_helper->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    <?php foreach ($_category->getParentCategories() as $parent): ?>
        <?php $_categories = $parent->getChildrenCategories() ?>
        <?php if (count($_categories) > 0): ?>
            <ul>
                <?php foreach($_categories as $category): ?>
                    <li class="sub-categories">
                        <?php if($category->getName() == $_category->getName()): ?><span class="selected-category" ><?php endif; ?>
                            <a href="<?php echo $_category_helper->getCategoryUrl($category) ?>"><?php echo $category->getName() ?></a>
                        <?php if($category->getName() == $_category->getName()): ?></span><?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
-->

<?php
    if(!Mage::getStoreConfig("porto_settings/category/fullwidth_description",$code)){
        if($_description=$_category->getDescription()){
?>
<div class="category-description std">
<?php
            echo $_helper->categoryAttribute($_category, $_description, 'description');
?>
</div>
<?php
        }
    }
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
