<div class="image-gallery-outer">
    <div class="image-detail">
        <ul id="masonry-loop"  class="image-gallery">
            <?php foreach ($this->getGalleryCollection() as $image): ?>
                <?php if ($image['gallery']) : ?>
                    <li class="gallery-item masonry-entry">
                        <div class="img-box">
                            <div class="img-box-inner">
                                <a class="imagegallery" href="<?php echo $image->getUrl(); ?>" title="<?php echo $image->getFile(); ?>"><img src="<?php echo $image->getUrl(); ?>" alt="<?php echo $image->getFile(); ?>"/></a>
                                <div class="gallery-desc-box">
                                    <div class="gallery-content">
                                        <h3 class="gallery-title">
                                         <?php echo $image->getFile(); ?>
                                        </h3>								
                                            <?php if ($image->getFile()): ?>
                                                <div class="gallery-desc">
                                                    <?php echo $data['image_description']; ?>
                                                </div>
                                            <?php endif; ?>								
                                            <a class="image-link gallery-block image-link<?php echo $catid; ?>" data-effect="mfp-move-horizontal" href="<?php echo $image->getUrl(); ?>" title="<?php echo $image->getFile(); ?>"><?php echo $image->getFile(); ?>
                                            <i class="fa"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <script type="text/javascript">
        jQuery(function ($) {
            // Gallery
            jQuery('.image-link<?php echo $catid; ?>.gallery-block').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true,
                    preload: function (e) {
                        var interval,
                                hasSize,
                                onHasSize = function () {
                                    if (hasSize)
                                        return;
                                    // we ignore browsers that don't support naturalWidth
                                    var naturalWidth = img[0].naturalWidth;

                                    if (window.devicePixelRatio > 1 && naturalWidth > 0) {
                                        img.css('max-width', naturalWidth / window.devicePixelRatio);
                                    }
                                    clearInterval(interval);
                                    hasSize = true;
                                },
                                onLoaded = function () {
                                    onHasSize();
                                },
                                onError = function () {
                                    onHasSize();
                                },
                                checkSize = function () {
                                    if (img[0].naturalWidth > 0) {
                                        onHasSize();
                                    }
                                },
                                img = $('<img />')
                                .on('load', onLoaded)
                                .on('error', onError)
                                // hd-image.jpg is optimized for the current pixel density
                                .attr('src', 'hd-image.jpg')
                                .appendTo(someContainer);
                        interval = setInterval(checkSize, 100);
                        checkSize();
                    }
                }
            });
        });
        jQuery(document).ready(function () {
            var $container = jQuery('#masonry-loop');
            var number;
            // initialize Isotope
            if ($container.width() < 5000 && $container.width() > 900) {
                number = 3;
            }
            if ($container.width() > 460 && $container.width() < 900) {
                number = 2;
            }
            if ($container.width() < 460) {
                number = 1;
            }
            var container1 = document.querySelector('#masonry-loop');
            //create empty var msnry
            var msnry;
            // initialize Masonry after all images have loaded
            imagesLoaded(container1, function () {
                msnry = new Masonry(container1, {
                    itemSelector: '.masonry-entry',
                    "gutter": 0,
                    "width": $container.width() / number
                });
            });
        });
    </script>
</div>